// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using studnt.ViewModel;

#nullable disable

namespace studnt.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230325183452_newtable")]
    partial class newtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("studnt.Model.Instructors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IInstructorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("IModuleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISecondName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("studnt.Model.Modules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulename")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("studnt.Model.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SAcadenicYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("SFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SRegistrationNumbrer")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSecondName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
